# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
