# Generated by Django 2.2 on 2019-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
