# Generated by Django 2.1.5 on 2019-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='delta',
            field=models.IntegerField(default=25),
        ),
    ]
