# Generated by Django 2.1.5 on 2019-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_match_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='rows_progress',
            new_name='nb_rows',
        ),
        migrations.AddField(
            model_name='match',
            name='rows_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
