# Generated by Django 2.1.5 on 2019-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20190414_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='delta',
            field=models.SmallIntegerField(default=100),
        ),
    ]
