# Generated by Django 2.2 on 2020-11-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_collection_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='has_popularity',
            field=models.BooleanField(default=True),
        ),
    ]
