# Generated by Django 2.2 on 2020-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_collection_has_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popularity',
            field=models.SmallIntegerField(default=5),
        ),
    ]
